apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod # Qualquer recurso com essa label
  ports:
    - port: 9000 # Ouvir : Despachar => nesse caso 80:80
      targetPort: 80 # agora ele ouve na 9000 e manda para 80